USE RISK_PORTFOLIO

--==========================================================STEP 1 - #STEP1_BASE 
DROP TABLE IF EXISTS #STEP1_BASE

SELECT 
	LOAN_ACCOUNT_NUMBER
	,DISBURSEMENT_DATE
	,FIRST_PAYMENT_DATE
	,LOAN_AMOUNT
	,PRINCIPAL_OUTSTANDING
	,DPD
	,DATEDIFF(MONTH,FIRST_PAYMENT_DATE,REPORT_DATE) + 1 AS PAYMENT_MONTH_NO
INTO #STEP1_BASE
FROM RISK_PORTFOLIO..FACT_LOAN_MANAGEMENT
WHERE REPORT_DATE >= FIRST_PAYMENT_DATE 
ORDER BY REPORT_DATE


--==========================================================STEP 2 - #STEP2_MAX_DPD
DROP TABLE IF EXISTS #STEP2_MAX_DPD

SELECT 
	LOAN_ACCOUNT_NUMBER
	,DISBURSEMENT_DATE
	,FIRST_PAYMENT_DATE
	,LOAN_AMOUNT
	,PRINCIPAL_OUTSTANDING
	,PAYMENT_MONTH_NO
	,MAX(DPD) AS MAX_DPD_IN_MONTH
INTO #STEP2_MAX_DPD
FROM [#STEP1_BASE]
WHERE PAYMENT_MONTH_NO BETWEEN 1 AND 3
GROUP BY	 
		LOAN_ACCOUNT_NUMBER
		,DISBURSEMENT_DATE
		,FIRST_PAYMENT_DATE
		,LOAN_AMOUNT
		,PRINCIPAL_OUTSTANDING
		,PAYMENT_MONTH_NO


--==========================================================STEP 3 - #STEP3_FLAGS
DROP TABLE IF EXISTS #STEP3_FLAG

SELECT
	LOAN_ACCOUNT_NUMBER
	,DISBURSEMENT_DATE
	,FIRST_PAYMENT_DATE
	,LOAN_AMOUNT
	,[FPD FLAG]	=		MAX(CASE WHEN PAYMENT_MONTH_NO = 1 AND MAX_DPD_IN_MONTH > 0 THEN 1 ELSE 0 END)
	,[SPD_FLAG] =		MAX(CASE WHEN PAYMENT_MONTH_NO = 2 AND MAX_DPD_IN_MONTH > 0 THEN 1 ELSE 0 END)
	,[TPD_FLAG] =		MAX(CASE WHEN PAYMENT_MONTH_NO = 3 AND MAX_DPD_IN_MONTH > 0 THEN 1 ELSE 0 END)
	,[FPD_FLAG_PRIN] =	MAX(CASE WHEN PAYMENT_MONTH_NO = 1 AND MAX_DPD_IN_MONTH > 0 THEN PRINCIPAL_OUTSTANDING ELSE 0 END)
	,[SPD_FLAG_PRIN] =	MAX(CASE WHEN PAYMENT_MONTH_NO = 2 AND MAX_DPD_IN_MONTH > 0 THEN PRINCIPAL_OUTSTANDING ELSE 0 END)
	,[TPD_FLAG_PRIN] =	MAX(CASE WHEN PAYMENT_MONTH_NO = 3 AND MAX_DPD_IN_MONTH > 0 THEN PRINCIPAL_OUTSTANDING ELSE 0 END)
	,[MAX_DPD_M1] =		MAX(CASE WHEN PAYMENT_MONTH_NO = 1							THEN MAX_DPD_IN_MONTH ELSE 0 END)
	,[MAX_DPD_M2] =		MAX(CASE WHEN PAYMENT_MONTH_NO = 2							THEN MAX_DPD_IN_MONTH ELSE 0 END)
	,[MAX_DPD_M3] =		MAX(CASE WHEN PAYMENT_MONTH_NO = 3							THEN MAX_DPD_IN_MONTH ELSE 0 END)
INTO #STEP3_FLAG
FROM [#STEP2_MAX_DPD]
GROUP BY 
		LOAN_ACCOUNT_NUMBER
		,DISBURSEMENT_DATE
		,FIRST_PAYMENT_DATE
		,LOAN_AMOUNT

--==========================================================STEP 4 - #STEP4_DEFAULT_METRIC

DROP TABLE IF EXISTS #STEP4_DEFAULT_METRIC

SELECT
	LOAN_ACCOUNT_NUMBER
	,DISBURSEMENT_DATE
	,FIRST_PAYMENT_DATE
	,[FPD FLAG]
	,SPD_FLAG
	,TPD_FLAG
	,MAX_DPD_M1
	,MAX_DPD_M2
	,MAX_DPD_M3
	,[DEFAULT LABEL] = CASE 
							WHEN [FPD FLAG]		= 1		AND SPD_FLAG = 1 AND TPD_FLAG = 1	THEN 'FPD + SPD + TPD'
							WHEN FPD_FLAG_PRIN	= 1		AND SPD_FLAG = 1					THEN 'FPD + SPD'
							WHEN SPD_FLAG		= 1		AND TPD_FLAG = 1					THEN 'SPD + TPD'
							WHEN [FPD FLAG]		= 1		AND TPD_FLAG = 1					THEN 'FPD + TPD'
							WHEN [FPD FLAG]		= 1											THEN 'FPD Only'
							WHEN SPD_FLAG		= 1											THEN 'SPD Only'
							WHEN TPD_FLAG		= 1											THEN 'TPD Only'
							ELSE																 'No Default' END

INTO #STEP4_DEFAULT_METRIC
FROM [#STEP3_FLAG]
ORDER BY LOAN_ACCOUNT_NUMBER


--==========================================================STEP 5 - #STEP4_DEFAULT_METRIC
DROP TABLE IF EXISTS #STEP5_36_LOANS
SELECT
	X1.*
INTO #STEP5_36_LOANS
FROM RISK_PORTFOLIO..FACT_LOAN_MANAGEMENT X1
WHERE NOT EXISTS
				(
				SELECT LOAN_ACCOUNT_NUMBER
				FROM [#STEP4_DEFAULT_METRIC] X2
				WHERE X1.LOAN_ACCOUNT_NUMBER = X2.LOAN_ACCOUNT_NUMBER
				)


DROP TABLE IF EXISTS #STEP5_36_LOANS_CHOT_EOMONTH

SELECT
	 X1.LOAN_ACCOUNT_NUMBER
	,X1.DISBURSEMENT_DATE
	,X1.FIRST_PAYMENT_DATE
	,X1.REPORT_DATE
	,X1.PRINCIPAL_OUTSTANDING
	,X1.DPD
	,[PAYMENT_MONTH_NO] = DATEDIFF(MONTH,X1.DISBURSEMENT_DATE,X1.REPORT_DATE) + 1 
INTO #STEP5_36_LOANS_CHOT_EOMONTH
FROM RISK_PORTFOLIO..FACT_LOAN_MANAGEMENT X1
WHERE EXISTS
			(
			SELECT
				DISTINCT LOAN_ACCOUNT_NUMBER
			FROM [#STEP5_36_LOANS] X2
			WHERE X1.LOAN_ACCOUNT_NUMBER = X2.LOAN_ACCOUNT_NUMBER
			)
	AND X1.REPORT_DATE = EOMONTH(X1.REPORT_DATE)
GROUP BY 
		X1.LOAN_ACCOUNT_NUMBER
		,X1.DISBURSEMENT_DATE
		,X1.FIRST_PAYMENT_DATE
		,X1.REPORT_DATE
		,X1.PRINCIPAL_OUTSTANDING
		,X1.DPD


--==========================================================STEP 6 - #STEP6_FPD_SPD_TPD_EWS

DROP TABLE IF EXISTS #STEP6_FPD_SPD_TPD_EWS 
		
SELECT X.*
INTO #STEP6_FPD_SPD_TPD_EWS
FROM 
		(
		SELECT
			*
		FROM [#STEP4_DEFAULT_METRIC]

		UNION ALL

		SELECT
			LOAN_ACCOUNT_NUMBER
			,DISBURSEMENT_DATE
			,FIRST_PAYMENT_DATE
			,[FPD FLAG]=		ISNULL(CAST(NULL AS NVARCHAR(200)), 0) 
			,[SPD_FLAG]=		ISNULL(CAST(NULL AS NVARCHAR(200)), 0)
			,[TPD_FLAG]=		ISNULL(CAST(NULL AS NVARCHAR(200)), 0)
			,[MAX_DPD_M1]=		ISNULL(CAST(NULL AS NVARCHAR(200)), 0)
			,[MAX_DPD_M2]=		ISNULL(CAST(NULL AS NVARCHAR(200)), 0)
			,[MAX_DPD_M3]=		ISNULL(CAST(NULL AS NVARCHAR(200)), 0)
			,[DEFAULT LABEL]=	'No Default'
		FROM [#STEP5_36_LOANS_CHOT_EOMONTH]
		) X



--[=============================CODE TỔNG=========================================]

DROP TABLE IF EXISTS #VINTAGE_LOSS_TO_SALE

SELECT 
	 X1.DISB_MONTH
	,X1.REPORT_DATE
	,X1.MOB
	,X1.ASSET_CLASSIFICATION
	,X2.PRODUCT_NAME
	,X2.REGION
	,X1.LOAN_AMOUNT
	,X1.PRINCIPAL_OUTSTANDING
	,[FPD > 10] = MAX(CASE WHEN X3.LOAN_ACCOUNT_NUMBER IS NOT NULL AND X3.MAX_DPD_M1 > 10 THEN 1 ELSE 0 END)
	,[SPD]		= MAX(CASE WHEN X3.LOAN_ACCOUNT_NUMBER IS NOT NULL AND X3.MAX_DPD_M2 BETWEEN 30 AND 60 THEN 1 ELSE 0 END)
	,[TPD]		= MAX(CASE WHEN X3.LOAN_ACCOUNT_NUMBER IS NOT NULL AND X3.MAX_DPD_M3 BETWEEN 60 AND 90 THEN 1 ELSE 0 END)
	,[NST90 - NON STARTER 90 DAYS]	= MAX(CASE WHEN X3.LOAN_ACCOUNT_NUMBER IS NOT NULL AND X3.[DEFAULT LABEL] IN ('FPD + SPD + TPD') THEN 1 ELSE 0 END)
	,[TLDP Nhóm 2 - Nợ cần chú ý]		=		SUM(CASE WHEN X1.ASSET_CLASSIFICATION = N'Nhóm 2 - Nợ cần chú ý' THEN PRINCIPAL_OUTSTANDING ELSE 0 END) * 0.05
	,[TLDP Nhóm 3 - Nợ không dưới tiêu chuẩn] =	SUM(CASE WHEN X1.ASSET_CLASSIFICATION = N'Nhóm 3 - Nợ không dưới tiêu chuẩn' THEN PRINCIPAL_OUTSTANDING ELSE 0 END) * 0.2
	,[TLDP Nhóm 4 - Nợ nghi ngờ] =				SUM(CASE WHEN X1.ASSET_CLASSIFICATION = N'Nhóm 4 - Nợ nghi ngờ' THEN PRINCIPAL_OUTSTANDING ELSE 0 END) * 0.5
	,[TLDP Nhóm 5 - Nợ có khả năng mất vốn] =	SUM(CASE WHEN X1.ASSET_CLASSIFICATION = N'Nhóm 5 - Nợ có khả năng mất vốn' THEN PRINCIPAL_OUTSTANDING ELSE 0 END) * 1
INTO #VINTAGE_LOSS_TO_SALE
FROM 
	(
	SELECT
		[DISB_MONTH] = CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23)
		,REPORT_DATE
		,[MOB] = DATEDIFF(MONTH,DISBURSEMENT_DATE,REPORT_DATE) + 1
		,LOAN_ACCOUNT_NUMBER
		,LOAN_AMOUNT
		,PRINCIPAL_OUTSTANDING
		,[ASSET_CLASSIFICATION] = CASE	WHEN DPD < 10 THEN					N'Nhóm 1 - Nợ đạt tiêu chuẩn'
										WHEN DPD >= 10 AND DPD <= 90 THEN	N'Nhóm 2 - Nợ cần chú ý'
										WHEN DPD >= 91 AND DPD <= 180 THEN	N'Nhóm 3 - Nợ không dưới tiêu chuẩn'
										WHEN DPD >= 181 AND DPD <= 360 THEN N'Nhóm 4 - Nợ nghi ngờ'
										ELSE								N'Nhóm 5 - Nợ có khả năng mất vốn' END
	FROM RISK_PORTFOLIO..FACT_LOAN_MANAGEMENT
	WHERE REPORT_DATE = EOMONTH(REPORT_DATE)
	) X1
LEFT JOIN RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE X2	ON X1.LOAN_ACCOUNT_NUMBER = X2.LOAN_ACCOUNT_NUMBER
LEFT JOIN [#STEP6_FPD_SPD_TPD_EWS] X3				ON X1.LOAN_ACCOUNT_NUMBER = X3.LOAN_ACCOUNT_NUMBER
GROUP BY
		 X1.DISB_MONTH
		,X1.REPORT_DATE
		,X1.MOB
		,X1.ASSET_CLASSIFICATION
		,X2.PRODUCT_NAME
		,X2.REGION
		,X1.LOAN_AMOUNT
		,X1.PRINCIPAL_OUTSTANDING



----1.Loss to sale qua các ký báo cáo (chốt cuối tháng). Tổng giá trị Loss to sale bao gồm (FPD > 10, SPD, TPD và Write-Off - NST90). Mẫu là tổng giá trị giải ngân đầu kỳ. (LOAN_AMOUNT)

SELECT
	DISB_MONTH
	,MOB
	,[SALE]							= SUM(LOAN_AMOUNT)
	,[FPD > 10]						= SUM(CASE WHEN [FPD > 10] = 1	THEN PRINCIPAL_OUTSTANDING ELSE 0 END)
	,[SPD]							= SUM(CASE WHEN SPD = 1			THEN PRINCIPAL_OUTSTANDING ELSE 0 END)
	,[TPD]							= SUM(CASE WHEN TPD = 1			THEN PRINCIPAL_OUTSTANDING ELSE 0 END)
	,[NST90 - NON STARTER 90 DAYS]	= SUM(CASE WHEN [NST90 - NON STARTER 90 DAYS] = 1 THEN PRINCIPAL_OUTSTANDING ELSE 0 END)
	,[LOSS]							= SUM(CASE WHEN [FPD > 10] = 1	THEN PRINCIPAL_OUTSTANDING ELSE 0 END)
									+ SUM(CASE WHEN SPD = 1			THEN PRINCIPAL_OUTSTANDING ELSE 0 END)
									+ SUM(CASE WHEN TPD = 1			THEN PRINCIPAL_OUTSTANDING ELSE 0 END)
									+ SUM(CASE WHEN [NST90 - NON STARTER 90 DAYS] = 1 THEN PRINCIPAL_OUTSTANDING ELSE 0 END)
	,[LOSS_TO_SALE]					= (SUM(CASE WHEN [FPD > 10] = 1	THEN PRINCIPAL_OUTSTANDING ELSE 0 END)
									+ SUM(CASE WHEN SPD = 1			THEN PRINCIPAL_OUTSTANDING ELSE 0 END)
									+ SUM(CASE WHEN TPD = 1			THEN PRINCIPAL_OUTSTANDING ELSE 0 END) 
									+ SUM(CASE WHEN [NST90 - NON STARTER 90 DAYS] = 1 THEN PRINCIPAL_OUTSTANDING ELSE 0 END)) * 100.0 / SUM(LOAN_AMOUNT)
FROM [#VINTAGE_LOSS_TO_SALE]
GROUP BY
		DISB_MONTH
		,MOB
ORDER BY
		(SUM(CASE WHEN [FPD > 10] = 1	THEN PRINCIPAL_OUTSTANDING ELSE 0 END)
									+ SUM(CASE WHEN SPD = 1			THEN PRINCIPAL_OUTSTANDING ELSE 0 END)
									+ SUM(CASE WHEN TPD = 1			THEN PRINCIPAL_OUTSTANDING ELSE 0 END) 
									+ SUM(CASE WHEN [NST90 - NON STARTER 90 DAYS] = 1 THEN PRINCIPAL_OUTSTANDING ELSE 0 END)) * 100.0 / SUM(LOAN_AMOUNT)


----2. Tổng dư nợ tổn thất liên tục 3 kỳ. Phần trăm tỷ lệ tổn thất trên tổng dư nợ đầu kỳ trong 1 năm gần nhất cho từng sản phẩm. Xếp hạng sản phẩm đang có trích lập dự phòng cao nhất
SELECT
            X1.PRODUCT_NAME
		   ,X1.NST90
		   ,[% NST90 - PER PRODUCT] = X1.NST90 * 100.0 / SUM(X1.NST90) OVER ()
		   ,X2.[TLDP Nhóm 2 - PER PRODUCT]
		   ,X2.[TLDP Nhóm 3 - PER PRODUCT]
		   ,X2.[TLDP Nhóm 4 - PER PRODUCT]
		   ,X2.[TLDP Nhóm 5 - PER PRODUCT]
FROM 
        (
				SELECT
					  PRODUCT_NAME
					 ,[NST90] 		           = SUM(CASE WHEN [NST90 - NON STARTER 90 DAYS]  = 1 THEN PRINCIPAL_OUTSTANDING ELSE 0 END) 
					 ,[LOSS_RATE]              = SUM(CASE WHEN [NST90 - NON STARTER 90 DAYS]  = 1 THEN PRINCIPAL_OUTSTANDING ELSE 0 END) / SUM(LOAN_AMOUNT)
					 ,LOAN_AMOUNT              = SUM(CASE WHEN [NST90 - NON STARTER 90 DAYS]  = 1 THEN LOAN_AMOUNT ELSE 0 END)
				FROM #VINTAGE_LOSS_TO_SALE
				WHERE YEAR(REPORT_DATE) = (SELECT YEAR(MAX(REPORT_DATE)) FROM #VINTAGE_LOSS_TO_SALE)
				GROUP BY PRODUCT_NAME
	    ) X1 
LEFT JOIN
	(
SELECT
       X.PRODUCT_NAME
	  ,[TLDP Nhóm 2 - PER PRODUCT] = [TLDP: Nhóm 2 - Nợ cần chú ý] * 100.0				/ SUM(X.[TLDP: Nhóm 2 - Nợ cần chú ý]) OVER ()
	  ,[TLDP Nhóm 3 - PER PRODUCT] = [TLDP: Nhóm 3 - Nợ dưới tiêu chuẩn'] * 100.0		/ SUM(X.[TLDP: Nhóm 3 - Nợ dưới tiêu chuẩn']) OVER ()
	  ,[TLDP Nhóm 4 - PER PRODUCT] = [TLDP: Nhóm 4 - Nợ nghi ngờ] * 100.0				/ SUM(X.[TLDP: Nhóm 4 - Nợ nghi ngờ]) OVER ()
	  ,[TLDP Nhóm 5 - PER PRODUCT] = [TLDP: Nhóm 5 - Nợ có khả năng mất vốn] * 100.0	/ SUM(X.[TLDP: Nhóm 5 - Nợ có khả năng mất vốn]) OVER ()
FROM 
         (
				SELECT
					   X.PRODUCT_NAME
					  ,[TLDP: Nhóm 2 - Nợ cần chú ý]           = SUM(X.[TLDP Nhóm 2 - Nợ cần chú ý])
					  ,[TLDP: Nhóm 3 - Nợ dưới tiêu chuẩn']    = SUM(X.[TLDP Nhóm 3 - Nợ không dưới tiêu chuẩn])
					  ,[TLDP: Nhóm 4 - Nợ nghi ngờ]            = SUM(X.[TLDP Nhóm 4 - Nợ nghi ngờ])
					  ,[TLDP: Nhóm 5 - Nợ có khả năng mất vốn] = SUM(X.[TLDP Nhóm 5 - Nợ có khả năng mất vốn])
				FROM #VINTAGE_LOSS_TO_SALE X
				GROUP BY X.PRODUCT_NAME 
		 ) X 
) X2 ON X1.PRODUCT_NAME = X2.PRODUCT_NAME


/*  

--3. Tính toán:
       - Được biết OPEX - Operating Expenditure (chi phí thuê văn phòng + chi phí trả lương nhân viên, vân vân) đang chiếm 10% trên tổng dư nợ đầu kỳ
	   - Tổng lãi thu được chiếm 50% trên dư nợ đầu kỳ (Phí trễ hạn, phí các thể loại, lãi cộng vô)
	   - Chi phí trích lập dự phòng qua các kỳ báo cáo.
	   - Loss to sale từ ý 1

CÔNG THỨC TÍNH TOÁN RA ĐƯỢC
--==========> LỢI NHUẬN THUẦN = TỔNG LÃI THU ĐƯỢC - OPEX - TỔN THẤT [LOSS] --> (FPD,SPD,TPD,WRITE OFF) 

*/  

SELECT
	 DISB_MONTH
	 ,MOB
	,PRODUCT_NAME
	,REGION
	,[REVENUE]									= SUM(LOAN_AMOUNT) * 0.5
	,[OPEX]										= SUM(LOAN_AMOUNT) * 0.1
	,[PROVISION]								= SUM([TLDP Nhóm 2 - Nợ cần chú ý])							 
												+ SUM([TLDP Nhóm 3 - Nợ không dưới tiêu chuẩn]) 
												+ SUM([TLDP Nhóm 4 - Nợ nghi ngờ])				
												+ SUM([TLDP Nhóm 5 - Nợ có khả năng mất vốn])	
	,[LOSS]										= SUM(CASE WHEN [FPD > 10] = 1	THEN PRINCIPAL_OUTSTANDING ELSE 0 END)
												+ SUM(CASE WHEN	SPD = 1			THEN PRINCIPAL_OUTSTANDING ELSE 0 END)
												+ SUM(CASE WHEN TPD = 1			THEN PRINCIPAL_OUTSTANDING ELSE 0 END)
												+ SUM(CASE WHEN [NST90 - NON STARTER 90 DAYS] = 1 THEN PRINCIPAL_OUTSTANDING ELSE 0 END)
	,[RISK-ADJUSTED RETURN]						= SUM(LOAN_AMOUNT) * 0.5 - SUM(LOAN_AMOUNT) * 0.1
												 -(SUM(CASE WHEN [FPD > 10] = 1	THEN PRINCIPAL_OUTSTANDING ELSE 0 END)
												+ SUM(CASE WHEN	SPD = 1			THEN PRINCIPAL_OUTSTANDING ELSE 0 END)
												+ SUM(CASE WHEN TPD = 1			THEN PRINCIPAL_OUTSTANDING ELSE 0 END)
												+ SUM(CASE WHEN [NST90 - NON STARTER 90 DAYS] = 1 THEN PRINCIPAL_OUTSTANDING ELSE 0 END))
FROM [#VINTAGE_LOSS_TO_SALE] X1
GROUP BY 
		 REGION
		 ,PRODUCT_NAME
		 ,DISB_MONTH
		 ,MOB
ORDER BY DISB_MONTH

